name: Deploy Docs

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install curl libcurl4-openssl-dev doxygen
    - name: autotools
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make docs
      run: |
        make docs
        touch docs/html/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: docs/html
