name: Testing

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install curl libcurl4-openssl-dev
    - name: autotools
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check


